/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BackPokemon: typeof import('./../components/back-pokemon.vue')['default']
    BattleMenu: typeof import('./../components/battle-menu.vue')['default']
    BattleMenuAttacks: typeof import('./../components/battle-menu/attacks.vue')['default']
    BattleMenuFight: typeof import('./../components/battle-menu/fight.vue')['default']
    BattleMenuMain: typeof import('./../components/battle-menu/main.vue')['default']
    FrontPokemon: typeof import('./../components/front-pokemon.vue')['default']
    PokemonStats: typeof import('./../components/pokemon-stats.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
